apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-app
  namespace: audio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-app
  template:
    metadata:
      labels:
        app: audio-app
    spec:
      containers:
        - name: audio-app
          image: image-registry.openshift-image-registry.svc:5000/audio-app/audio-app:latest
          ports:
            - containerPort: 8080
          env:
            # Endpoint e credenciais do S3
            - name: S3_ENDPOINT_URL
              value: "https://s3.openshift-storage.svc:443"  # Endpoint conforme especificado no OBC
            - name: BUCKET_NAME
              value: "audio-storage-59a4534d-3066-40b6-941b-91691d8231b3"  # Nome do bucket especificado no OBC
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: audio-storage
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: audio-storage
                  key: AWS_SECRET_ACCESS_KEY
            # Chave de API do OpenAI usando Secret
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: audio-app-service
  namespace: audio-app
spec:
  selector:
    app: audio-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
